<?php
function template_suggestions_menu_alter(&$items) {
	//dpm($items);
}
// suggest new template files
function template_suggestions_preprocess(&$vars,$hook) {
	if ($hook == 'page') {
		//dpm(menu_get_item($_GET['q']));
	}
	if ($hook == 'node') {
		$node = $vars['node'];

		if ($vars['is_front']) {
			$vars['theme_hook_suggestions'][] = 'node__' . $node->type . '_front';
		}
		
    $vars['theme_hook_suggestions'][] = 'node__' . $node->type . '_' . $vars['view_mode'];
	}
	if ($hook == 'page') {
	
		// if page request comes from AJAX  (tested with jQuery)
		if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH']=="XMLHttpRequest") {
  		$vars['theme_hook_suggestions'][] = 'page_ajax';
		}
		
	}
	
}
/*
	Implements hook_entity_info_alter().
*/
function template_suggestions_entity_info_alter(&$entities) {
	$entities['node']['view modes']['modal'] = array(
    'label' => 'Modal',
    'custom settings' => TRUE,
  );
    
  $entities['node']['view modes']['widget'] = array(
    'label' => 'Widget',
    'custom settings' => TRUE,
  );
  
  $entities['node']['view modes']['widgetalt'] = array(
    'label' => 'Widget Alternate',
    'custom settings' => TRUE,
  );
}

?>